### PR TITLE
feat: Added Support For Applications Api #55

### PR DESCRIPTION
**Pull request by sugan0tech**

### CODE REVIEW

**Comment by sugan0tech** [comment]
@andrii-bodnar  can you review this PR?

**Comment by andrii-bodnar** [comment]
@sugan0tech thank you! The CI has failed, could you please take a look?

**Comment by sugan0tech** [comment]
yeah updated it, can you rerun the pipeline?

**Comment by andrii-bodnar** [comment]
@sugan0tech still failing

**Comment by sugan0tech** [comment]
image
fixed now.

**Review by andrii-bodnar — APPROVED** [review]
@sugan0tech thank you!

**Pull request merged**
