### PR TITLE
feat: Add config to enable instant file download

### PR DESCRIPTION
**Pull request by artem-vavilov**
Issue: https://github.com/crowdin/crowdin-api-client-ruby/issues/66

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Hi @artem-vavilov, thanks for the contribution!

This download file functionality doesn't fit well into this API client, and it's something that's unique to this client. None of our other API clients have it, so I've even thought about removing it.

 I'm not sure if it's a good idea to introduce the new config parameter, so I'd suggest changing the behavior a little bit.

Let's download the file only in cases when the `destination` parameter is specified. In that case, we'll still return the path to the downloaded file.

If the `destination` parameter is not passed - return the full API response.

For example, with the `destination`:

```ruby
crowdin.download_file(file_id: your_file_id, destination: your_destination, project_id: your_project_id)

# -> should return the downloaded file path.
```

Without the destination:

```ruby
crowdin.download_file(file_id: your_file_id, project_id: your_project_id)

# -> should return an object from the response

# {
#   "url": "https://production-enterprise-importer.downloads.crowdin.com/992000002/2/14.xliff?......",
#   "expireIn": "2019-09-20T10:31:21+00:00",
#   "etag": "ebd69a1b7e4c23e6d17891a491c94f832e0c82e4692dedb35a6cd1e624b62"
# }
```

Please let me know what you think about this!

**Comment by artem-vavilov** [comment]
> If the `destination` parameter is not passed - return the full API response.

@andrii-bodnar I also considered this option but rejected it because it would dramatically change the behavior of some methods.

However, if you don't mind, I'm happy to implement this!

**Comment by andrii-bodnar** [comment]
@artem-vavilov yes, it could be a bit risky. We'll try to release it by adding a warning message to release notes about this change.

Could you please take a look at the #67 PR as well?

It would be great if we could release both of these fixes within a single release.

**Comment by artem-vavilov** [comment]
New PR: https://github.com/crowdin/crowdin-api-client-ruby/pull/69

**Pull request closed without merging**
