### PR TITLE
feat: Support concordance and alignment API endpoints

### PR DESCRIPTION
**Pull request by laasem**
Addresses https://github.com/crowdin/crowdin-api-client-ruby/issues/39 by adding the following 3 new API endpoints and their corresponding unit tests:

- [api.projects.glossaries.concordance.post](https://developer.crowdin.com/api/v2/#operation/api.projects.glossaries.concordance.post)
- [api.projects.translations.alignment.post](https://developer.crowdin.com/api/v2/#operation/api.projects.translations.alignment.post)
- [api.projects.tms.concordance.post](https://developer.crowdin.com/api/v2/#operation/api.projects.tms.concordance.post)

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@laasem thanks a lot for your contribution!

The CI has failed, could you please take a look? https://github.com/crowdin/crowdin-api-client-ruby/actions/runs/4462294126

Most of the CI issues seem related to the quotes style.

**Comment by laasem** [comment]
@andrii-bodnar Thanks for your comments! I've addressed them; howeve, the linting still fails due to the two wrapper describe blocks in [glossaries_spec.rb](https://github.com/laasem/crowdin-api-client-ruby/blob/main/spec/api_resources/glossaries_spec.rb#L3-L4) being too long. What would you suggest breaking them up as part of this PR or a separate one?

**Comment by andrii-bodnar** [comment]
@laasem I think that the best option here is to break the `Default endpoints` into smaller groups of endpoints. For example, `Default endpoints` (all the glossary-related endpoints including new concordance search), `Concept endpoints`, `Term endpoints`

**Comment by andrii-bodnar** [comment]
It would be great if you could do it within the current PR, just to not break the `main` pipeline

**Comment by laasem** [comment]
@andrii-bodnar Thanks for your suggestion - I've implemented it and I think it should work now.

**Comment by andrii-bodnar** [comment]
@laasem thanks a lot for the contribution, looks good to me! 🚀

**Review by andrii-bodnar — APPROVED** [review]

**Pull request merged**
